import {
  Folder,
  Briefcase,
  Book,
  Dumbbell,
  Rocket,
  Code,
  Palette,
  Calendar,
  GraduationCap,
  HeartPulse,
  Laptop,
  Monitor,
  ShoppingCart,
  Plane,
  Music,
  Camera,
  Gamepad2,
  Utensils,
  Clapperboard,
  PenTool,
  Users,
  Target,
  Trophy,
  Lightbulb,
  type LucideIcon,
} from "lucide-react"

export const icons: Record<string, LucideIcon> = {
  folder: Folder,
  briefcase: Briefcase,
  book: Book,
  dumbbell: Dumbbell,
  rocket: Rocket,
  code: Code,
  palette: Palette,
  calendar: Calendar,
  graduationCap: GraduationCap,
  heartPulse: HeartPulse,
  laptop: Laptop,
  monitor: Monitor,
  shoppingCart: ShoppingCart,
  plane: Plane,
  music: Music,
  camera: Camera,
  gamepad2: Gamepad2,
  utensils: Utensils,
  clapperboard: Clapperboard,
  penTool: PenTool,
  users: Users,
  target: Target,
  trophy: Trophy,
  lightbulb: Lightbulb,
}

export const iconOptions = [
  "folder",
  "briefcase",
  "book",
  "dumbbell",
  "rocket",
  "code",
  "palette",
  "calendar",
  "graduationCap",
  "heartPulse",
  "laptop",
  "monitor",
  "shoppingCart",
  "plane",
  "music",
  "camera",
  "gamepad2",
  "utensils",
  "clapperboard",
  "penTool",
  "users",
  "target",
  "trophy",
  "lightbulb",
] as const
